In [28]:
import pandas as pd
import numpy as np

In [29]:
df=pd.read_csv("heart_disease_dataset.csv", sep=";")

In [30]:
df.head()

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0   63    1                3                     145          233   
1   37    1                2                     130          250   
2   41    0                1                     130          204   
3   56    1                1                     120          236   
4   57    0                0                     120          354   

   fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                    1         0                      150   
1                    0         1                      187   
2                    0         0                      172   
3                    0         1                      178   
4                    0         1                      163   

   exercise_induced_angina  st_depression  st_slope  num_major_vessels  \
0                        0            2.3         0                  0   
1                        0            3.5         0                  0   
2                        0            1.4         2                  0   
3                        0            0.8         2                  0   
4                        1            0.6         2                  0   

   thalassemia  target  
0            1       1  
1            2       1  
2            2       1  
3            2       1  
4            2       1

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      303 non-null    int64  
 1   sex                      303 non-null    int64  
 2   chest_pain_type          303 non-null    int64  
 3   resting_blood_pressure   303 non-null    int64  
 4   cholesterol              303 non-null    int64  
 5   fasting_blood_sugar      303 non-null    int64  
 6   rest_ecg                 303 non-null    int64  
 7   max_heart_rate_achieved  303 non-null    int64  
 8   exercise_induced_angina  303 non-null    int64  
 9   st_depression            303 non-null    float64
 10  st_slope                 303 non-null    int64  
 11  num_major_vessels        303 non-null    int64  
 12  thalassemia              303 non-null    int64  
 13  target                   303 non-null    int64  
dtypes: float64(1), int64(13)
m

In [32]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate_achieved    0
exercise_induced_angina    0
st_depression              0
st_slope                   0
num_major_vessels          0
thalassemia                0
target                     0
dtype: int64

In [33]:
from sklearn.model_selection import train_test_split 

In [34]:
X = df.drop('target',axis=1).values
y = df['target'].values.reshape(-1,1)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42, test_size = 0.2)

In [45]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
    return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN      = x
        self.W1   = np.random.rand(self.IN.shape[1],6) 
        self.W2   = np.random.rand(6,4)
        self.W3   = np.random.rand(4,1)
        self.y          = y
        self.OUT     = np.zeros(self.y.shape)
        self.learning_rate = 0.3

    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))

    def back_propagate(self):
        print(self.HIDDEN_LAYER_1.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output),self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)))
        d_W1 = np.dot(self.IN.T,  (np.dot(np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2),self.W2.T) * sigmoid_derivative(self.HIDDEN_LAYER_1)))

        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3

    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 2:", self.W3)
    
    
    def print_output(self):
        print(self.output)
        
    def predict(self,x):
        HIDDEN_LAYER_1 = sigmoid(np.dot(x, self.W1))
        HIDDEN_LAYER_2 = sigmoid(np.dot(HIDDEN_LAYER_1, self.W2))
        output = sigmoid(np.dot(HIDDEN_LAYER_2, self.W3))
        return output

In [46]:
ann = ArtificialNeuralNetwork(X,y)
epochs = 500
learning_rate = 0.1
ann.train(epochs,learning_rate)

[[0.19151553 0.33604355 0.1603742  ... 0.9492213  0.27100954 0.12068801]
 [0.88250286 0.96174883 0.13833817 ... 0.89561096 0.21966692 0.0709171 ]
 [0.11934044 0.08890594 0.05419134 ... 0.89325471 0.885794   0.04142715]
 [0.60250992 0.46035332 0.08907706 ... 0.93720165 0.50410533 0.17679556]
 [0.41961204 0.25522759 0.06241148 ... 0.975073   0.14866486 0.22162257]
 [0.93447556 0.83361132 0.07685772 ... 0.996555   0.20583473 0.1275444 ]]
[[0.19441323 0.34841456 0.18504863 ... 0.93906617 0.22608746 0.13218327]
 [0.88578179 0.96342099 0.15375941 ... 0.88240423 0.19349919 0.07606084]
 [0.12266648 0.09463916 0.06277813 ... 0.87642815 0.86052032 0.04558235]
 [0.60512724 0.47659613 0.10314693 ... 0.92613346 0.45082712 0.19060318]
 [0.42140763 0.26573284 0.07074545 ... 0.97066893 0.13030205 0.2327995 ]
 [0.93553762 0.84457613 0.09216714 ... 0.99570586 0.17000871 0.13997027]]
[[0.2047895  0.33803827 0.1543281  ... 0.95414744 0.26433928 0.11980824]
 [0.88878339 0.96001955 0.13171257 ... 0.90534694

  9.73177437e-01 2.19264911e-02]]
[[6.25467364e-05 1.09848000e-01 8.85898620e-04 ... 9.99998802e-01
  8.85846773e-01 4.88425068e-05]
 [9.99972423e-01 9.95662704e-01 1.26150697e-01 ... 9.98871954e-01
  4.96102947e-01 8.36960335e-04]
 [4.61127332e-01 8.79053557e-01 3.30070779e-04 ... 9.98967193e-01
  9.99359269e-01 4.41817313e-03]
 [9.97359527e-01 9.97821224e-01 2.46320558e-06 ... 1.00000000e+00
  9.99987593e-01 1.88782876e-05]
 [8.91067087e-01 9.99150268e-01 6.14950268e-02 ... 4.06524640e-03
  9.25950490e-03 2.81453496e-02]
 [9.98958742e-01 9.99263074e-01 1.58949975e-02 ... 9.97646258e-01
  9.73174172e-01 2.19792745e-02]]
[[6.24227215e-05 1.10183479e-01 8.82249565e-04 ... 9.99998816e-01
  8.85889534e-01 4.85649247e-05]
 [9.99972646e-01 9.95696397e-01 1.26095780e-01 ... 9.98869773e-01
  4.95458689e-01 8.33056628e-04]
 [4.61514836e-01 8.79078718e-01 3.28610205e-04 ... 9.98969768e-01
  9.99359975e-01 4.41454734e-03]
 [9.97360917e-01 9.97820608e-01 2.44483207e-06 ... 1.00000000e+00
  9.9998

In [47]:
print(X_test, y_test)

[[ 0.29046364  0.68100522 -0.93851463  1.04952029  0.57466203 -0.41763453
  -1.00583187 -1.6463164   1.43548113 -0.37924438 -0.64911323  0.26508221
  -2.14887271]
 [ 1.39335191  0.68100522 -0.93851463 -0.3783023   0.14950142  2.394438
   0.89896224  0.58393935 -0.69663055 -0.7243226  -0.64911323  1.24459328
   1.12302895]
 [-0.92271345  0.68100522 -0.93851463  0.47839125  1.25105391 -0.41763453
   0.89896224 -1.29647236  1.43548113  0.65599028 -0.64911323  1.24459328
   1.12302895]
 [ 0.62133012  0.68100522  1.00257707  0.47839125 -1.18395686 -0.41763453
  -1.00583187  0.23409531 -0.69663055  1.69122495 -0.64911323 -0.71442887
  -0.51292188]
 [-0.48155814  0.68100522  1.00257707  0.47839125 -0.25633371 -0.41763453
   0.89896224  0.58393935 -0.69663055 -0.37924438 -0.64911323  0.26508221
   1.12302895]
 [ 1.72421839  0.68100522  1.00257707  1.62064933  0.43938366 -0.41763453
   0.89896224 -1.6463164   1.43548113  1.60495539 -0.64911323  0.26508221
   1.12302895]
 [ 0.18017482  0.6810052

In [50]:
ann.predict(X_test[4])

array([0.01406295])