In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("heart_disease_dataset.csv", sep=";")

In [3]:
df.head()

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0   63    1                3                     145          233   
1   37    1                2                     130          250   
2   41    0                1                     130          204   
3   56    1                1                     120          236   
4   57    0                0                     120          354   

   fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                    1         0                      150   
1                    0         1                      187   
2                    0         0                      172   
3                    0         1                      178   
4                    0         1                      163   

   exercise_induced_angina  st_depression  st_slope  num_major_vessels  \
0                        0            2.3         0                  0   
1                        0            3.5         0                  0   
2                        0            1.4         2                  0   
3                        0            0.8         2                  0   
4                        1            0.6         2                  0   

   thalassemia  target  
0            1       1  
1            2       1  
2            2       1  
3            2       1  
4            2       1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      303 non-null    int64  
 1   sex                      303 non-null    int64  
 2   chest_pain_type          303 non-null    int64  
 3   resting_blood_pressure   303 non-null    int64  
 4   cholesterol              303 non-null    int64  
 5   fasting_blood_sugar      303 non-null    int64  
 6   rest_ecg                 303 non-null    int64  
 7   max_heart_rate_achieved  303 non-null    int64  
 8   exercise_induced_angina  303 non-null    int64  
 9   st_depression            303 non-null    float64
 10  st_slope                 303 non-null    int64  
 11  num_major_vessels        303 non-null    int64  
 12  thalassemia              303 non-null    int64  
 13  target                   303 non-null    int64  
dtypes: float64(1), int64(13)
m

In [5]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate_achieved    0
exercise_induced_angina    0
st_depression              0
st_slope                   0
num_major_vessels          0
thalassemia                0
target                     0
dtype: int64

In [6]:
X = df.drop('target',axis=1).values
y = df['target'].values.reshape(-1,1)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split 

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42, test_size = 0.2)

In [10]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
    return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN      = x
        self.W1   = np.random.rand(self.IN.shape[1],6) 
        self.W2   = np.random.rand(6,4)
        self.W3   = np.random.rand(4,1)
        self.y          = y
        self.OUT     = np.zeros(self.y.shape)
        self.learning_rate = 0.3

    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))

    def back_propagate(self):
        print(self.HIDDEN_LAYER_1.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output),self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)))
        d_W1 = np.dot(self.IN.T,  (np.dot(np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2),self.W2.T) * sigmoid_derivative(self.HIDDEN_LAYER_1)))

        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3

    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 2:", self.W3)
    
    def predict(self,x):
        HIDDEN_LAYER_1 = sigmoid(np.dot(x, self.W1))
        HIDDEN_LAYER_2 = sigmoid(np.dot(HIDDEN_LAYER_1, self.W2))
        output = sigmoid(np.dot(HIDDEN_LAYER_2, self.W3))
        return output
    
    def print_output(self):
        print(self.output)
        

In [11]:
ann = ArtificialNeuralNetwork(X,y)
epochs = 500
learning_rate = 0.1
ann.train(epochs,learning_rate)

[[0.32010286 0.20566728 0.17799989 ... 0.97285913 0.62699376 0.06752763]
 [0.20381749 0.44923557 0.05759157 ... 0.93291999 0.47831564 0.14548736]
 [0.81204822 0.80897623 0.04862315 ... 0.98708988 0.24788525 0.03820115]
 [0.37393372 0.33047068 0.07055289 ... 0.9829671  0.17052711 0.06933804]
 [0.54664622 0.77625513 0.21513939 ... 0.97543279 0.13527621 0.25767842]
 [0.88099402 0.1755454  0.13990913 ... 0.97650936 0.53397992 0.23258804]]
[[0.32577595 0.21381438 0.19608208 ... 0.9687995  0.58372969 0.07253745]
 [0.20681093 0.46349638 0.06656173 ... 0.92186123 0.42000833 0.15833194]
 [0.81762459 0.81743569 0.05574869 ... 0.9847652  0.21466268 0.04155155]
 [0.36887629 0.35095736 0.08518494 ... 0.97878338 0.13630241 0.07650623]
 [0.55896016 0.78860283 0.24479355 ... 0.97083202 0.11155265 0.27788643]
 [0.88431083 0.18501225 0.16007529 ... 0.97212838 0.48101739 0.24974578]]
[[0.3312883  0.20826477 0.18230694 ... 0.97214966 0.59854303 0.070103  ]
 [0.21100869 0.44999133 0.05833163 ... 0.93511229

  9.66170204e-01 5.27483549e-02]]
[[2.94605808e-03 2.75746727e-01 3.48850343e-04 ... 9.99936708e-01
  9.99992921e-01 1.62831429e-05]
 [8.67574843e-08 2.58133207e-02 1.12465539e-06 ... 9.99999993e-01
  1.00000000e+00 3.89062812e-06]
 [2.21032449e-03 9.99952242e-01 3.22443897e-02 ... 9.99999687e-01
  9.99997702e-01 2.16822565e-05]
 [5.42837203e-01 6.37508875e-02 8.35968250e-03 ... 9.99102237e-01
  9.47559084e-01 3.44974424e-02]
 [2.66867283e-01 9.99897468e-01 3.58550995e-02 ... 9.99999980e-01
  9.53741127e-01 1.11502530e-02]
 [3.69735152e-01 6.48926219e-01 6.07916230e-02 ... 9.99983179e-01
  9.66005189e-01 5.33246962e-02]]
[[3.14863858e-03 2.86361125e-01 3.25953010e-04 ... 9.99938254e-01
  9.99992500e-01 1.54892492e-05]
 [9.14493198e-08 2.74730543e-02 1.03832895e-06 ... 9.99999993e-01
  1.00000000e+00 3.68982932e-06]
 [1.91717330e-03 9.99950806e-01 3.50649383e-02 ... 9.99999688e-01
  9.99997864e-01 2.21424225e-05]
 [5.09039489e-01 5.98330257e-02 8.62907793e-03 ... 9.99098087e-01
  9.5062

In [12]:
print(X_test, y_test)

[[ 0.29046364  0.68100522 -0.93851463  1.04952029  0.57466203 -0.41763453
  -1.00583187 -1.6463164   1.43548113 -0.37924438 -0.64911323  0.26508221
  -2.14887271]
 [ 1.39335191  0.68100522 -0.93851463 -0.3783023   0.14950142  2.394438
   0.89896224  0.58393935 -0.69663055 -0.7243226  -0.64911323  1.24459328
   1.12302895]
 [-0.92271345  0.68100522 -0.93851463  0.47839125  1.25105391 -0.41763453
   0.89896224 -1.29647236  1.43548113  0.65599028 -0.64911323  1.24459328
   1.12302895]
 [ 0.62133012  0.68100522  1.00257707  0.47839125 -1.18395686 -0.41763453
  -1.00583187  0.23409531 -0.69663055  1.69122495 -0.64911323 -0.71442887
  -0.51292188]
 [-0.48155814  0.68100522  1.00257707  0.47839125 -0.25633371 -0.41763453
   0.89896224  0.58393935 -0.69663055 -0.37924438 -0.64911323  0.26508221
   1.12302895]
 [ 1.72421839  0.68100522  1.00257707  1.62064933  0.43938366 -0.41763453
   0.89896224 -1.6463164   1.43548113  1.60495539 -0.64911323  0.26508221
   1.12302895]
 [ 0.18017482  0.6810052

  -0.51292188]] [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]]


In [13]:
ann.predict(X_test[4])

array([0.00085502])